"""
Django settings for multi_tenant_shop project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import socket

# Base directory of the project.
BASE_DIR = Path(__file__).resolve().parent.parent
# Loads environment variables from the .env file.
load_dotenv(os.path.join(BASE_DIR, ".env"))

# ==============================================================================
# CORE DJANGO SETTINGS
# ==============================================================================

SECRET_KEY = os.getenv('SECRET_KEY')
# Enables debug mode for development.
DEBUG = True
# Allows all incoming requests in development.
ALLOWED_HOSTS = ['*']

# ==============================================================================
# MULTI-TENANCY CONFIGURATION (django-tenants)
# ==============================================================================

# --- DATABASE ROUTER ---
# This tells Django to use the TenantSyncRouter, which is essential for
# directing database queries to the correct tenant schema.
DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# --- MIDDLEWARE ---
# The TenantMainMiddleware (or a custom version) must be the first middleware.
# It inspects the incoming request's hostname to determine the correct tenant.
MIDDLEWARE = [
    # Replaced the default TenantMainMiddleware with our custom version.
    # The custom middleware inherits from the original but adds an approval check.
    # 'django_tenants.middleware.main.TenantMainMiddleware',
    'multi_tenant_shop.middleware.tenant_middleware.CustomTenantMiddleware',
    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Make sure to keep the Debug Toolbar middleware for development.
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

# --- SHARED AND TENANT APPS ---
# These apps live in the 'public' schema and are shared by all tenants.
SHARED_APPS = [
    'django_tenants',
    'store', # Our main app for managing tenants and products.
    'store_management', # App for store administration.
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'crispy_forms',
    'crispy_bootstrap5',
    'debug_toolbar',
    
    # REST Framework, JWT, and API docs packages which are common for all tenants.
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
] 

# These apps will have their tables created in EACH tenant's schema.
TENANT_APPS = [
    'django_filters',
    'django_elasticsearch_dsl',
    # Other tenant-specific apps should be added here.
]

# The correct way to combine app lists while preserving order.
INSTALLED_APPS = SHARED_APPS + TENANT_APPS


# ==============================================================================
# STANDARD DJANGO CONFIGURATION (Continues)
# ==============================================================================

ROOT_URLCONF = 'multi_tenant_shop.urls'
PUBLIC_SCHEMA_URLCONF = 'multi_tenant_shop.urls_public' 

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context_processors.tenant_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'multi_tenant_shop.wsgi.application'

# --- DATABASE CONFIGURATION ---
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': os.getenv('DATABASE_NAME'),
        'USER': os.getenv('DATABASE_USER'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD'),
        'HOST': os.getenv('DATABASE_HOST'),
        'PORT': os.getenv('DATABASE_PORT'),
    }
}

# ==============================================================================
# CACHING CONFIGURATION
# ==============================================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # Connects to the 'redis' service defined in docker-compose.yml.
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# --- PASSWORD VALIDATION ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- INTERNATIONALIZATION ---
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- STATIC FILES ---
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

# --- DEFAULT PRIMARY KEY ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# MULTI-TENANCY MODEL DEFINITIONS
# ==============================================================================

# --- TENANT MODEL DEFINITION ---
# This explicitly tells django-tenants which models in our project
# should be used for defining Tenants and their Domains.
TENANT_MODEL = "store.Tenant"
TENANT_DOMAIN_MODEL = "store.Domain"

AUTH_USER_MODEL = 'store.User'

CART_SESSION_ID = 'cart'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# ==============================================================================
# ELASTICSEARCH CONFIGURATION
# ==============================================================================
ELASTICSEARCH_DSL = {
    'default': {
        'hosts': f"http://{os.getenv('ELASTICSEARCH_HOST')}:9200",
    },
}

# ==============================================================================
# DJANGO REST FRAMEWORK (DRF) CONFIGURATION
# ==============================================================================
REST_FRAMEWORK = {
    # Sets JWT as the default authentication class.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Sets the default permission policy.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# ==============================================================================
# JWT CONFIGURATION (djangorestframework-simplejwt)
# ==============================================================================
SIMPLE_JWT = {
    # Sets the lifespan of the access token.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    # Sets the lifespan of the refresh token.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Enables token blacklisting on logout.
    "BLACKLIST_AFTER_ROTATION": True,
}

# ==============================================================================
# API DOCUMENTATION CONFIGURATION (drf-spectacular)
# ==============================================================================
SPECTACULAR_SETTINGS = {
    # Sets the title of the OpenAPI documentation page.
    'TITLE': 'Multi-Tenant E-commerce API',
    # Describes the purpose of the API.
    'DESCRIPTION': 'API for managing products, users, and orders in a multi-tenant e-commerce platform.',
    # Defines the API version.
    'VERSION': '1.0.0',
    # Specifies the server URL.
    'SERVE_URL': 'api/schema/',
}

STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY')

# Dynamically finds the host's IP address to allow the Debug Toolbar to appear.
hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
INTERNAL_IPS = [ip[: ip.rfind(".")] + ".1" for ip in ips] + ["127.0.0.1"]

# --- EMAIL CONFIGURATION (for development) ---
# Tells Django to print emails to the console instead of sending them.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- CELERY CONFIGURATION ---
# Uses Redis as the message broker.
CELERY_BROKER_URL = 'redis://redis:6379/0'
CELERY_RESULT_BACKEND = 'redis://redis:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# --- MEDIA FILES CONFIGURATION (for user-uploaded content) ---
# The absolute filesystem path to the directory that will hold user-uploaded files.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
