# Generated by Django 5.2.5 on 2026-05-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_order_options_tenant_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_chat_override', models.BooleanField(default=False, help_text='Bypass AI agent and route to live human agent')),
            ],
        ),
    ]
