# Generated by Django 5.2.5 on 2026-05-12 23:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_storesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_currency',
            field=models.CharField(default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sale_currency',
            field=models.CharField(default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='local_currency',
            field=models.CharField(default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='target_profit_margin',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_tenants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subdomain',
            field=models.SlugField(blank=True, max_length=63, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='target_profit_margin',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant_role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='ExchangeRateCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('quote_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=18)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('base_currency', 'quote_currency')},
            },
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('support', 'Support'), ('customer', 'Customer')], max_length=20)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='TRY', max_length=3)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='store.productvariant')),
            ],
            options={
                'ordering': ['changed_at'],
                'indexes': [models.Index(fields=['product_variant', 'changed_at'], name='store_produ_product_0f1fa0_idx')],
            },
        ),
    ]
